name: Build and Deploy LaTeX Document

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up LaTeX environment
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: Compile LaTeX document
        run: |
          mkdir build
          pdflatex -output-directory=build main.tex
          bibtex build/main.aux
          pdflatex -output-directory=build main.tex
          pdflatex -output-directory=build main.tex

      - name: Verify compiled PDF
        run: |
          if [ ! -f build/main.pdf ]; then
            echo "PDF file was not generated successfully"
            exit 1
          fi

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdf
          path: build/main.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy PDF to build branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b build
          cp build/main.pdf main.pdf
          git add main.pdf
          git commit -m "Deploy compiled PDF"
          git push origin build --force
